### ISSUE TITLE
FrostedGlass doesnt work

### ISSUE THREAD

**Issue by xalgenyt** [DiscordStyles/FrostedGlass#6]
Simply put, it doesnt make my discord transparent, it makes it dark gray. I dont know how to fix that, please send help.

**Comment by Gibbu** [comment]
Make sure the Transparency Option is enabled in BetterDiscord settings. If not, enable it, close Discord and open it again.

**Comment by olegatronik12** [comment]
Yeah, background image is gray... I tryed to set a computer file and it doesn't work

**Comment by olegatronik12** [comment]
That's url's not working:
https://discordstyles.github.io/RadialStatus/base.css
https://discordstyles.github.io/FrostedGlass/base.css

**Comment by MrDuckz** [comment]
I don't know what they did... But I was working and changing some stuff when suddenly the background stopped being shown. 
I can't really see the lines they changed or if it's just some bug or someone forgot to add something.

**Comment by Gibbu** [comment]
All my themes got a structure change meaning the `base.css` file doesn't exist anymore.

All you have to do is just change the end of the url from `base.css` to `dist/[ThemeName].css`.
Example with Frosted Glass:
![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)

**Comment by olegatronik12** [comment]
> All my themes got a structure change meaning the `base.css` file doesn't exist anymore.
> 
> All you have to do is just change the end of the url from `base.css` to `dist/[ThemeName].css`.
> Example with Frosted Glass:
> ![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)

wow! it work! thx

**Comment by MrDuckz** [comment]
Fixed it, thanks!

**Comment by RinLovesYou** [comment]
that was a pretty weirdchamp change

**Comment by bruh360** [comment]
> All my themes got a structure change meaning the `base.css` file doesn't exist anymore.
> 
> All you have to do is just change the end of the url from `base.css` to `dist/[ThemeName].css`.
> Example with Frosted Glass:
> ![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)

I changed the import url but frostedglass still doesn't work for me

**Comment by kallezz** [comment]
> > All my themes got a structure change meaning the `base.css` file doesn't exist anymore.
> > All you have to do is just change the end of the url from `base.css` to `dist/[ThemeName].css`.
> > Example with Frosted Glass:
> > ![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)
> 
> I changed the import url but frostedglass still doesn't work for me

same..

**Comment by Gibbu** [comment]
Here's the [newest theme file](https://github.com/DiscordStyles/FrostedGlass/blob/master/dist/FrostedGlass.theme.css).  
Just look how that does it.

**Comment by L1ZGitHub** [comment]
The fix works but horizontal server list broke

**Comment by Gibbu** [comment]
Do the exact same thing but do "HorizontalServerList" instead of "FrostedGlass"

**Comment by ObviousWhale** [comment]
i did everything but im still not able to change theme or how blury it is

**Comment by Gibbu** [comment]
Just use this: https://gibbu.me/editor.

It's a tool that I made to help edit themes.
